backend:
  name: github
  repo: capriosa/phenomic-cms
  branch: master

public_folder: "/assets"
media_folder: "content/assets"
publish_mode: editorial_workflow

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    sort: "date:desc" # Default is title:asc
    slug: "{{slug}}"
    card: {type: "alltype", text: "title"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hero", name: "hero", widget: "image", optional: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "string", default: "Post"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
